### PR TITLE
Adding Glyphs source

### PR DESCRIPTION
**Pull request by aaronbell**
Created a proper source, and did additional modifications for release on Google Fonts.

Please review the font here:
[ShizuruFont-Regular.ttf.zip](https://github.com/shibuyafont/shizuru-font/files/5556734/ShizuruFont-Regular.ttf.zip)

If you have any comments / feedback, please let me know! :)

### CODE REVIEW

**Comment by aaronbell** [comment]
Hi, could you merge this PR in, or add me as a collaborator so that I can do it instead? 
Thanks!

**Comment by shibuyafont** [comment]
Hi, aaronbell. Sorry for late response...
Thank you very very very much for your corporation!!! 
Would you like to add you as a collaborator instead me?  I am not sure how to do it by myself.

**Comment by aaronbell** [comment]
Yes, please add me as a collaborator on all your Google Fonts repositories and I'll take care of them :).

**Comment by shibuyafont** [comment]
I did it.　Could you check it?

**Comment by aaronbell** [comment]
Yes, thank you!

**Pull request merged**
